### ISSUE TITLE
Support for Python 3.5?

### ISSUE THREAD

**Issue by afhaque** [wingchen/citipy#1]
Great Library! Very handy. Worked well for a Python 2.7 project.

Unfortunately, not so well with a Python 3.5 project. Import doesn't seem to work. I'll look at your code to see if this a quick fix

```
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-1-b49a8be8dcc2> in <module>()
      9 
     10 # Incorporated citipy to determine city based on latitude and longitude
---> 11 from citipy import citipy
     12 
     13 # Output File (CSV)

C:\Users\Ahmed\Anaconda3\envs\PythonData\lib\site-packages\citipy\citipy.py in <module>()
     24 
     25     # discrad the headers
---> 26     cities.next()
     27 
     28     # populate geo points into kdtree

AttributeError: '_csv.reader' object has no attribute 'next'
```

**Comment by wingchen** [comment]
Thank you for the bug report. I will do a quick fix for python 3.5 after this week too.
Meanwhile, PRs are welcome.

**Comment by afhaque** [comment]
Just submitted the fix! Passed the test on my end. 

https://github.com/wingchen/citipy/pull/2

**Comment by wingchen** [comment]
I merged it. Looking good.
Will package up for pip in a bit. Thanks a lot.

**Comment by wingchen** [comment]
released: https://pypi.python.org/pypi/citipy/0.0.5
