### ISSUE TITLE
The "Maxmind" URL is not valid. 

### ISSUE THREAD

**Issue by TomBerton** [wingchen/citipy#3]
When you click the [Maxmind](https://www.maxmind.com/en/free-world-cities-database) URL, it returns: 

<img width="961" alt="Screen Shot 2019-08-01 at 9 22 12 AM" src="https://user-images.githubusercontent.com/9907572/62301446-4596e600-b43e-11e9-883e-95dd0a8a7662.png">

**Comment by MxAshUp** [comment]
Is this the same data set? https://dev.maxmind.com/geoip/geoip2/geolite2/

Looks like it's now behind a registration wall (EULA updates) - still free though.

**Comment by MxAshUp** [comment]
I had trouble finding the same datasets with maxmind, but the other link (http://download.geonames.org/export/dump/) seems to have the same dataset @wingchen used in citipy. in fact there's more data in there too that was trimmed out, so if you need other city info, grab http://download.geonames.org/export/dump/cities500.zip and sort through it.

**Comment by wingchen** [comment]
sorry for the very late response. I merged your PR in. 
https://github.com/wingchen/citipy/pull/5

If you think this issue is addressed, could you please help close it? thanks
